name: gogoget
favicon: null
layout_spectrum: 0.08069988479837775
typography_spectrum: 0.9816323609557003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7825697639491409
  lightness: 0.8675346150994301
  saturation: 0.6584758567623794
  rhythmicContrast: 0.3179785287939012
purpose: []
